using UnityEngine;
using System.Collections;
using UnityStandardAssets.Characters.ThirdPerson;

public class Enemy : MonoBehaviour, IDamageable {

	[SerializeField] float maxHealthPoints = 100f;
	[SerializeField] float chaseRadius = 6f;
	[SerializeField] float attackRadius = 4f;

	[SerializeField] float damagePerShot = 9f;
	[SerializeField] float secondsBetweenShots = 1f;
	[SerializeField] GameObject projectileToUse;
	[SerializeField] GameObject projectileSocket;
	[SerializeField] Vector3 aimOffset = new Vector3(0, 1f, 0);

	bool isAttacking = false;
    
	float currentHealthPoints = 100f;

	AICharacterControl aiCharacterControl = null;
	GameObject player = null;

	public float healthAsPercentage {
		get { 
			return currentHealthPoints / maxHealthPoints;
		}
	}
		
	void Start () {
		player = GameObject.FindGameObjectWithTag ("Player");
		aiCharacterControl = GetComponent<AICharacterControl> ();
		currentHealthPoints = maxHealthPoints;

	}

	void Update () {
		float distanceToPlayer = Vector3.Distance (player.transform.position, transform.position);

		if (distanceToPlayer <= attackRadius && !isAttacking) {

			isAttacking = true;
			InvokeRepeating ("SpawnProjectiles", 0f, secondsBetweenShots); // TODO switch to coroutines
		}
		if (distanceToPlayer > attackRadius) {

			isAttacking = false;
			CancelInvoke ();
		}

		if (distanceToPlayer <= chaseRadius) {
			aiCharacterControl.SetTarget (player.transform);
		} else {
			aiCharacterControl.SetTarget (transform);
		}
	}

	public void TakeDamage (float damage)
	{
		currentHealthPoints = Mathf.Clamp (currentHealthPoints - damage, 0f, maxHealthPoints);
				if (currentHealthPoints <= 0) {
					Destroy (gameObject);
				}
	}

	void SpawnProjectiles ()
	{
		GameObject newProjectile = Instantiate (projectileToUse, projectileSocket.transform.position, Quaternion.identity);
		Projectile projectileComponent = newProjectile.GetComponent<Projectile> ();
		projectileComponent.SetDamage (damagePerShot);

		Vector3 unitVectorToPlayer = (player.transform.position + aimOffset - projectileSocket.transform.position).normalized;
		newProjectile.GetComponent<Rigidbody> ().velocity = unitVectorToPlayer * projectileComponent.projectileSpeed;
	}

	void OnDrawGizmos () {

		// Draw attack sphere
		Gizmos.color = new Color(255f, 0, 0, .5f);
		Gizmos.DrawWireSphere (transform.position, attackRadius);

		// Draw chase sphere
		Gizmos.color = new Color(0, 0, 255f, .5f);
		Gizmos.DrawWireSphere (transform.position, chaseRadius);

	}
}
